name: login
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #carousel_slider
  carousel_slider: ^4.2.1

  #RXDART
  rxdart: ^0.27.7

  #FIREBASE
  firebase_storage: ^11.0.8
  firebase_auth: ^4.2.1
  firebase_core: ^2.3.0
  cloud_firestore: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  assets:
  - assets/images/

  uses-material-design: true
